### ISSUE TITLE
mobile

### ISSUE THREAD

**Issue by yuvalk** [sinelaw/watchbat#1]
any chance you can make it look alright on mobile device?

**Comment by sinelaw** [comment]
It's ugly as it is, but it should be usable on mobile devices (uses bootstrap)
did you try it?

**Comment by yuvalk** [comment]
yes, tried it, and the buttons are so small, I couldnt press them..
you can try for yourself if you want at:
http://54.172.204.187:1337/

**Comment by sinelaw** [comment]
Yes there's a problem...

**Comment by sinelaw** [comment]
should be fixed by 637413e - can you try again?

**Comment by yuvalk** [comment]
much better, I'll open a new issue on the rest
