### ISSUE TITLE
gps is recorded only once

### ISSUE THREAD

**Issue by yuvalk** [sinelaw/watchbat#2]
supposed to sample the gps on every observation

**Comment by sinelaw** [comment]
Did you check it?
It supposedly works (I couldn't check it) because it uses [Gelocation.watchPosition()](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition) to track positions.

**Comment by yuvalk** [comment]
no, I have just reviewed the code, probably just my miss-understanding.
